# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Run Example
      run: dotnet run -c Release --no-build --project Ryoken.Extensions.Hosting.ExampleConsole
    - name: Pack NuPkg
      run: dotnet pack --no-restore --no-build -c Release
    - name: Publish NuPkg to Github Packages
      run: dotnet nuget push "Ryoken.Extensions.Hosting/bin/Release/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
    - name: Publish Symbols to Github Packages
      run: dotnet nuget push "Ryoken.Extensions.Hosting/bin/Release/*.snupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
    - name: Publish NuPkg to NuGet.org
      run: dotnet nuget push "Ryoken.Extensions.Hosting/bin/Release/*.nupkg" --api-key ${{ secrets.NUGETORG_API_KEY }}  --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish Symbols to NuGet.org
      run: dotnet nuget push "Ryoken.Extensions.Hosting/bin/Release/*.snupkg" --api-key ${{ secrets.NUGETORG_API_KEY }}  --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v1.4.3
      with:
        subject-path: "Ryoken.Extensions.Hosting/bin/Release/*.nupkg"

